package com.pedrofernandez.appmovilludoteca.utils;

public class Mensajes {

    //PETICIONES
    public final static String PETICION_MAPA_LUDOTECAS_MOVIL = "P47SHOWLUDOTECASMOVIL";
    public final static String PETICION_REGISTRO_MAYOR_MOVIL = "P48REGISTROMAYORMOVIL";
    public final static String PETICION_REGISTRO_MENOR_MOVIL = "P49REGISTROMENORMOVIL";
    public final static String PETICION_LOGIN_CLIENTE_MOVIL = "P50LOGINCLIENTEMOVIL";
    public final static String PETICION_INSCRIBIRSE_LUDOTECA_MOVIL = "P57INSCRIBIRSELUDOTECA";
    public final static String PETICION_OBTENER_ACTIVIDADES_LUDOTECA_MOVIL = "P58OBTENERACTIVIDADESLUDOTECA";
    public final static String PETICION_INSCRIBIRSE_ACTIVIDAD_LUDOTECA_MOVIL = "P59INSCRIBIRSEACTIVIDADLUDOTECA";
    public final static String PETICION_PAGO_ACTIVIDAD_REALIZADA_MOVIL ="P60PAGOACTIVIDADREALIZADA";
    public final static String PETICION_OBTENER_ACTIVIDADES_INSCRITAS_MOVIL = "P61OBTENERACTIVIDADESINSCRITAS";
    public final static String PETICION_ABANDONAR_ACTIVIDAD_MOVIL = "P62ABANDONARACTIVIDAD";
    public final static String PETICION_OBTENER_ESTADO_CLIENTE_MOVIL = "P63OBTENERESTADOCLIENTE";
    public final static String PETICION_ACTUALIZAR_CLIENTE_MENOR_MOVIL = "P64ACTUALIZARCLIENTEMENOR";
    public final static String PETICION_ACTUALIZAR_CLIENTE_MAYOR_MOVIL = "P65ACTUALIZARCLIENTEMAYOR";

    //PETICIONES CORRECTAS
    public static final String PETICION_MAPA_LUDOTECAS_MOVIL_CORRECTA = "C47SHOWLUDOTECASMOVILCORRECTA";
    public static final String PETICION_REGISTRO_MAYOR_MOVIL_CORRECTO = "C48REGISTROMAYORMOVILCORRECTO";
    public final static String PETICION_REGISTRO_MENOR_MOVIL_CORRECTO = "C49REGISTROMENORMOVIL";
    public final static String PETICION_LOGIN_CLIENTE_MOVIL_CORRECTO = "C50LOGINCLIENTEMOVIL";
    public final static String PETICION_INSCRIBIRSE_LUDOTECA_MOVIL_CORRECTO_INSCRITO = "C57INSCRIBIRSELUDOTECAINSCRITO";
    public final static String PETICION_INSCRIBIRSE_LUDOTECA_MOVIL_CORRECTO_PREINSCRITO = "C57INSCRIBIRSELUDOTECAPREINSCRITO";
    public final static String PETICION_OBTENER_ACTIVIDADES_LUDOTECA_MOVIL_CORRECTO = "C58OBTENERACTIVIDADESLUDOTECA";
    public final static String PETICION_INSCRIBIRSE_ACTIVIDAD_LUDOTECA_MOVIL_CORRECTO = "C59INSCRIBIRSEACTIVIDADLUDOTECA";
    public final static String PETICION_OBTENER_ACTIVIDADES_INSCRITAS_MOVIL_CORRECTO ="C61OBTENERACTIVIDADESINSCRITAS";
    public final static String PETICION_ABANDONAR_ACTIVIDAD_MOVIL_CORRECTO = "C62ABANDONARACTIVIDAD";
    public final static String PETICION_ACTUALIZAR_CLIENTE_MENOR_MOVIL_CORRECTO = "C64ACTUALIZARCLIENTEMENOR";
    public final static String PETICION_ACTUALIZAR_CLIENTE_MAYOR_MOVIL_CORRECTO = "C65ACTUALIZARCLIENTEMAYOR";


    //PETICIONES INCORRECTAS
    public final static String PETICION_REGISTRO_MAYOR_MOVIL_ERROR = "E48REGISTROMAYORMOVILERROR";
    public final static String PETICION_REGISTRO_MENOR_MOVIL_ERROR = "E49REGISTROMENORMOVIL";
    public final static String PETICION_INSCRIBIRSE_LUDOTECA_MOVIL_ERROR_INSCRITO = "E57INSCRIBIRSELUDOTECAINSCRITO";
    public final static String PETICION_INSCRIBIRSE_LUDOTECA_MOVIL_ERROR_NO_CONFIRMADO = "E57INSCRIBIRSELUDOTECANOCONFIRMADO";
    public final static String PETICION_INSCRIBIRSE_ACTIVIDAD_LUDOTECA_MOVIL_ERROR_PREINSCRITO = "E59INSCRIBIRSEACTIVIDADLUDOTECAPREINSCRIPCION";
    public final static String PETICION_INSCRIBIRSE_ACTIVIDAD_LUDOTECA_MOVIL_ERROR_VALIDAR = "E59INSCRIBIRSEACTIVIDADLUDOTECAVALIDAR";
    public final static String PETICION_INSCRIBIRSE_ACTIVIDAD_LUDOTECA_MOVIL_ERROR_INSCRIPCIONLUDOTECA = "E59INSCRIBIRSEACTIVIDADLUDOTECAINSCRIPCION";
    public final static String PETICION_INSCRIBIRSE_ACTIVIDAD_LUDOTECA_MOVIL_ERROR_INSCRIPCIONACTIVIDAD = "E59INSCRIBIRSEACTIVIDADLUDOTECAINSCRIPCIONACTIVIDAD";
    public final static String PETICION_INSCRIBIRSE_ACTIVIDAD_LUDOTECA_MOVIL_ERROR_SINESPACIO = "E59INSCRIBIRSEACTIVIDADLUDOTECAESPACIO";
    public final static String PETICION_ABANDONAR_ACTIVIDAD_MOVIL_ERROR = "E62ABANDONARACTIVIDAD";
    public final static String PETICION_ACTUALIZAR_CLIENTE_MENOR_MOVIL_ERROR = "E64ACTUALIZARCLIENTEMENOR";
    public final static String PETICION_ACTUALIZAR_CLIENTE_MAYOR_MOVIL_ERROR = "E65ACTUALIZARCLIENTEMAYOR";










}
